name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Bicep Build (main)
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./bicep/workloads/main.bicep

      - name: Bicep Build (builder)
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./bicep/workloads/builder.bicep
